set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
# vcpkg 清理构建环境；只允许本地配方明确需要的两个非秘密路径进入。
set(VCPKG_ENV_PASSTHROUGH TANSR_CPP_DEPENDENCY_PREFIX TANSR_CPP_DEPENDENCY_PREFIX_DEBUG)
